# GitHub Pages configuration
theme: jekyll-theme-minima
name: Welcome to the Borg | Collective GmbH
title: We are the Borg
description: Welcome to the Borg | Borg Collective GmbH
email: contact@borg.id                
twitter_username: hivedotone
github_username:  hive-one